config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions',
  omniauth_callbacks: 'users/omniauth_callbacks'   
  }

  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
    get "register/new", :to => "register/registrations#new"
  end
  
  root "tops#index"
  resources :login, only: [:new]
  
  namespace :mypage do
    resources :logout, only: [:index]
  end
  
  namespace :signup do
    resources :sms_confirmation, only: [:new, :create]
    resources :address, only: [:new, :create]
    resources :credit, only: [:new, :create]
    resources :first_step, only: [:new]
  end

   namespace :product do
    resources :exhibit, only: [:new]
  end
  
end

app/controllers/signup/address_controller.rb
class Signup::AddressController < ApplicationController
  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to new_signup_credit_path
    else
      render new_signup_address_path
    end 
  end

  private

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :prefecture, :city, :address_number, :building, :gender, :tel).merge(user_id: current_user.id)
    end
end

app/controllers/signup/credit_controller.rb
class Signup::CreditController < ApplicationController
  def new
    @credit = Credit.new
  end

  def create
    @credit = Credit.new(credit_params)
    if @credit.save
      render "signup/credit/create"
    else
      render new_signup_credit_path
    end 
  end

  private

    def credit_params
      params.require(:credit).permit(:number, :expiration_date, :secure_code).merge(user_id: current_user.id)
    end
end

app/controllers/signup/first_step_controller.rb
class Signup::FirstStepController < ApplicationController
  def new
  end
end

app/controllers/signup/sms_confirmation_controller.rb
class Signup::SmsConfirmationController < ApplicationController
  def new
    @profile = Profile.new
  end

  def create
    session[:profile_tel] = profile_params[:tel]
    redirect_to new_signup_address_path
  end

  private
  def profile_params
    params.require(:profile).permit(:tel)
  end
end

app/views/signup/address/new.html.erb
<h2>住所入力</h2>
<%= form_for [ @profile], url: signup_address_index_path do |f| %>
  <div class="field">
    <%= f.label :first_name %>お名前<br />
    <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %>
    <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %>
  </div>
  <div class="field">
    <%= f.label :first_name_kana %>お名前<br />
    <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana" %>
    <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana" %>
  </div>
  <div class="field">
    <%= f.label :postal_code %>郵便番号<br />
    <%= f.number_field :postal_code, autofocus: true, autocomplete: "postal_code" %>
  </div>
  <div class="field">
    <%= f.label :prefecture %>都道府県<br />
    <%= f.number_field :prefecture, autofocus: true, autocomplete: "prefecture" %>
  </div>
  <div class="field">
    <%= f.label :city %>市区町村<br />
    <%= f.text_field :city, autofocus: true, autocomplete: "city" %>
  </div>
  <div class="field">
    <%= f.label :address_number %>番地<br />
    <%= f.number_field :address_number, autofocus: true, autocomplete: "address_number" %>
  </div>
  <div class="field">
    <%= f.label :building %>建物<br />
    <%= f.text_field :building, autofocus: true, autocomplete: "building" %>
  </div>
  <div class="field">
    <%= f.label :tel %>電話<br />
    <%= f.number_field :tel, autofocus: true, autocomplete: "tel" %>
  </div>
  <div class="actions">
    <%= f.submit "次に進む" %>
  </div>
<% end %>