config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions',
  omniauth_callbacks: 'users/omniauth_callbacks'   
  }

  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
    get "register/new", :to => "register/registrations#new"
  end
  
  root "tops#index"
  resources :login, only: [:new]
  
  namespace :mypage do
    resources :logout, only: [:index]
  end
  
  namespace :signup do
    resources :sms_confirmation, only: [:new, :create]
    resources :address, only: [:new, :create]
    resources :credit, only: [:new, :create]
    resources :first_step, only: [:new]
  end

   namespace :product do
    resources :exhibit, only: [:new]
  end
  
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

  def index
  end
  
end

app/views/tops/index.html.erb
<header>
  <div class="header__top">
    <div class="header__top__left">
      <h1>メルカリロゴ</h1>
    </div>
    <div class="header__top__right">
      <p>何かお探しですか</p>
    </div>
  </div>
  <div class="header__content">
    <div class="header__content__left">
      <p>カテゴリーから探す</p>
      <p>ブランドから探す</p>
    </div>
    <div class="header__content__right">
      <%= link_to "新規会員登録", new_signup_first_step_path %>
      <%= link_to "ログイン", new_login_path %>
      <%= link_to "マイページ", mypage_logout_index_path%>
    </div>
  </div>
</header>