config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions',
  omniauth_callbacks: 'users/omniauth_callbacks'   
  }

  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
    get "register/new", :to => "register/registrations#new"
  end
  
  root "tops#index"
  resources :login, only: [:new]
  
  namespace :mypage do
    resources :logout, only: [:index]
  end
  
  namespace :signup do
    resources :sms_confirmation, only: [:new, :create]
    resources :address, only: [:new, :create]
    resources :credit, only: [:new, :create]
    resources :first_step, only: [:new]
  end

   namespace :product do
    resources :exhibit, only: [:new]
  end
  
end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :user
  validates :number, :expiration_date, :secure_code, presence: true
end

app/controllers/signup/address_controller.rb
class Signup::AddressController < ApplicationController
  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
      redirect_to new_signup_credit_path
    else
      render new_signup_address_path
    end 
  end

  private

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :prefecture, :city, :address_number, :building, :gender, :tel).merge(user_id: current_user.id)
    end
end

app/controllers/signup/credit_controller.rb
class Signup::CreditController < ApplicationController
  def new
    @credit = Credit.new
  end

  def create
    @credit = Credit.new(credit_params)
    if @credit.save
      render "signup/credit/create"
    else
      render new_signup_credit_path
    end 
  end

  private

    def credit_params
      params.require(:credit).permit(:number, :expiration_date, :secure_code).merge(user_id: current_user.id)
    end
end

app/controllers/signup/first_step_controller.rb
class Signup::FirstStepController < ApplicationController
  def new
  end
end

app/controllers/signup/sms_confirmation_controller.rb
class Signup::SmsConfirmationController < ApplicationController
  def new
    @profile = Profile.new
  end

  def create
    session[:profile_tel] = profile_params[:tel]
    redirect_to new_signup_address_path
  end

  private
  def profile_params
    params.require(:profile).permit(:tel)
  end
end

app/views/signup/credit/create.html.erb
<h1>会員登録完了</h1>
<p>ありがとうございます。<br>会員登録が完了しました。</p>
<%= link_to "メルカリを始める", root_path %>

app/views/signup/credit/new.html.erb
<h2>支払い方法</h2>
<%= form_for [ @credit], url: signup_credit_index_path do |f| %>
  <div class="field">
    <%= f.label :number %>カード番号<br />
    <%= f.number_field :number, autofocus: true, autocomplete: "number" %>
  </div>
  <div class="field">
    <%= f.label :expiration_date %>有効期限<br />
    <%= f.number_field :expiration_date, autofocus: true, autocomplete: "expiration_date" %>
  </div>
  <div class="field">
    <%= f.label :secure_code %>セキュリティコード<br />
    <%= f.text_field :secure_code, autofocus: true, autocomplete: "secure_code" %>
  </div>
  <div class="actions">
    <%= f.submit "次に進む" %>
  </div>
<% end %>