config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions',
  omniauth_callbacks: 'users/omniauth_callbacks'   
  }

  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
    get "register/new", :to => "register/registrations#new"
  end
  
  root "tops#index"
  resources :login, only: [:new]
  
  namespace :mypage do
    resources :logout, only: [:index]
  end
  
  namespace :signup do
    resources :sms_confirmation, only: [:new, :create]
    resources :address, only: [:new, :create]
    resources :credit, only: [:new, :create]
    resources :first_step, only: [:new]
  end

   namespace :product do
    resources :exhibit, only: [:new]
  end
  
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :images #(CarrierWave使用時)
  has_many_attached :images #(Active::Storage使用時)
  has_one :dealing
  belongs_to :user
  belongs_to :category
  belongs_to :brand
end

app/controllers/product/exhibit_controller.rb
class Product::ExhibitController < ApplicationController
  def new
    @product = Product.new
  end
end

app/views/product/exhibit/new.html.erb
<%= form_for(@product, url: new_product_exhibit_path) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, autocomplete: "on" %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :password, autocomplete: "on" %>
  </div>
  <div class="field">
    <%= f.label :detail %><br />
    <%= f.text_field :detail, autofocus: true, autocomplete: "on" %>
  </div>
  <div class="field">
    <%= f.label :condition %><br />
    <%= f.number_field :condition, autocomplete: "on" %>
  </div>
  <div class="actions">
    <%= f.submit "登録" %>
  </div>
<% end %>